#!/bin/bash
#Desciption : function +-*/
#Writeen by Rico
#Verison 1.00

function CALCULATOR ()
{
if [ $2 == 'multiply' ]	
then
	let Summary=$1*$3
elif [ $2 == 'divide' ]
then
	let Summary=$1*$3
fi

if [ $4 == 'multiply' ]
then
	if [ -z $Summary ]
	then
		let Summary=$3*$5
	elif [ -n $Summary ]
	then
		let Summary=$Summary*$5
	fi
elif [ $4 == 'divide' ]
then
	if [ -z $Summary ]
        then
                 let Summary=$3/$5
         elif [ -n $Summary ]
         then
		let Summary=$Summary/$5
	fi
fi


case $2 in
add )
	let Summary=$1+$3
;;
esac


echo $Summary
}

read -p "give me number: " yourNumA
read -p "you wanna add subtract multiply divide ? " yourCalculateB
read -p "give me number: " yourNumC
read -p "you wanna add subtract multiply divide ? " yourCalculateD
read -p "give me number: " yourNumE

CALCULATOR $yourNumA $yourCalculateB $yourNumC $yourCalculateD $yourNumE

exit 0

